"""add_hybrid_fields_to_messages

Revision ID: 6fa172fbbec3
Revises: 
Create Date: 2026-05-01 18:49:39.630836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa172fbbec3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'user1_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversations', 'user2_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'conversations', 'users', ['user1_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['user2_id'], ['id'])
    op.add_column('messages', sa.Column('client_message_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_client_message_id'), 'messages', ['client_message_id'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_messages_client_message_id'), table_name='messages')
    op.drop_column('messages', 'status')
    op.drop_column('messages', 'client_message_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.alter_column('conversations', 'user2_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversations', 'user1_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
