"""add_image_reaction_deleted

Revision ID: ae5d5e0079d1
Revises: 6fa172fbbec3
Create Date: 2026-05-03 12:30:27.621479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5d5e0079d1'
down_revision: Union[str, Sequence[str], None] = '6fa172fbbec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('reaction', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'reaction')
    op.drop_column('messages', 'image_url')
    # ### end Alembic commands ###
